### PR TITLE
Better filters

### PR DESCRIPTION
**Pull request by tlwr**

### CODE REVIEW

**Comment by tlwr** [comment]
I took another look at this, what do you think the behaviour of multiple filters should be:

```
person:toby title:cve
```
> should show all cve stories worked on by toby

or

> should show all cve stories or those worked on by toby

right now it is neither 👐

**Comment by tlwr** [comment]
Yolo merging this PR because it is better but not perfect than current, based on a conv with Andy in slack:

```
toby.lornewelch-richards [16:27 Uhr]
Shall we yolo merge this pr https://github.com/alphagov/paas-rubbernecker/pull/59
tlwr

andy.hunt [16:28 Uhr]
https://media.giphy.com/media/UqZ4imFIoljlr5O2sM/giphy.gif
```

**Comment by richardTowers** [comment]
Don't let your dreams be dreams

**Pull request merged**
